### PR TITLE
Pushing ipu-nf-cni

### PR DESCRIPTION
**Pull request by palade**
This PR adds the ipu-nf-cni code.

### CODE REVIEW

**Review by Eoghan1232 — APPROVED** [review]
lgtm

**Comment by Eoghan1232** [comment]
tested locally - APF's moved to container, and made the dummy calls to dummy ipu manager printing the HW address and Interface name.

**Comment by davecremins** [comment]
Is this PR valid anymore?

**Comment by ahalimx86** [comment]
> Is this PR valid anymore?

DPU Operator will have separate CNI for NF. So, we probably don't need this. But we can merge this PR and keep in the repo.

**Comment by palade** [comment]
> > Is this PR valid anymore?
> 
> DPU Operator will have separate CNI for NF. So, we probably don't need this. But we can merge this PR and keep it in the repo.

@davecremins @ahalimx86 If this functionality is enable through the DPU Operator then I can close the PR. The branch will still be available for review at a later date.

**Comment by palade** [comment]
Closing as functionality has been provided by the DPU operator.

**Pull request closed without merging**
