### PR TITLE
Adding changes for linux networking packages 1.6 and 1.8

### PR DESCRIPTION
**Pull request by saynb**
* Artifacts for 1.6 and 1.8 linux networking
* Changes to Dockerfile to enable changing p4 program with only change in Makefile env variable

### CODE REVIEW

**Comment by sudhar-krishnakumar** [comment]
@saynb , Just curious, so did you try to change the package-name, and rebuild the linux P4 networking package artifacts for each release 1.6 and 1.8, so that naming is more standard, versus...just taking the default package names.

**Comment by saynb** [comment]
> Just curious, so did you try to change the package-name, and rebuild the linux P4 networking package artifacts for each release 1.6 and 1.8, so that naming is more standard, versus...just taking the default package names.

No I had to rename names of all the files like context.json. Bringing everything to the default names will change a lot of things

**Comment by saynb** [comment]
The original name is present in the context.json. But AFAIK, it is not used for any runtime validation in the stack today in driver and everything runs fine. However, for easier dev purposes, I see your point. I can raise a later PR to rename all artifacts, including rh_mvp one so that it is easier to P4 develop and replace the artifacts easily than having to rename files every time

**Comment by sudhar-krishnakumar** [comment]
@saynb ok sounds good.

**Review by sudhar-krishnakumar — APPROVED** [review]
@saynb , per our chat, like name change in context.json  can be done later thro a different PR.

**Pull request merged**
