### PR TITLE
Updating p4rt-ctl binary

### PR DESCRIPTION
**Pull request by saynb**
* Updating p4rt-ctl binary with 2024-08 from 2023-11
* Adding few files to gitignore
* Updating p4runtime whl file in repo with 2024-08
* ipuplugin Dockerfile changes
  * Adding new builder stage for gRPC python building
  * cygrpc library being pulled has debug symbols adding 300MB so stripping them.
  * Removing ENV variables as not needed
  * Upgrading Base OS image from Alpine 3.19.1 to 3.19.4

### CODE REVIEW

**Comment by sudhar-krishnakumar** [comment]
@saynb there are some go-static- analysis checks that are failing for the Dockerfile.

**Comment by saynb** [comment]
> @saynb there are some go-static- analysis checks that are failing for the Dockerfile.

Yes working on them

**Comment by sudhar-krishnakumar** [comment]
@saynb , not sure, why those env variables were there for proxy settings. Are we sure, its okay to remove them.

**Comment by saynb** [comment]
> @saynb , not sure, why those env variables were there for proxy settings. Are we sure, its okay to remove them.

Yes. The way these proxy settings were supposed to work is for the runtime environment and the build environment. The place where it was added earlier was only benefitting the build stage. After removing, all that is required is that the terminal where you execute `make image`, the proxy environment variables are exported there, so no change in the build process as we needed to export the variables anyway. For runtime, the proxy settings where the docker/podman run is initiated will take effect, just as it was earlier, so no change there.
Testing done:
1.  `make imagex` on x86.
2. `make image` on arm64

**Review by sudhar-krishnakumar — APPROVED** [review]

**Pull request merged**
